### ISSUE TITLE
Issue with input fields inside <details> block

### ISSUE THREAD

**Issue by Elias-Black** [rilwis/bamboo#4]
Thank you for your amazing work, the theme looks great!

I tried using it for a slightly unconventional blog and encountered an issue:

1. The input fields inside the `<details>` block are not visually highlighted and blend with the background
<img width="844" alt="Image" src="https://github.com/user-attachments/assets/de29abf4-eb40-45ac-bf0e-9ecd60b43599" />

2. When clicking on an input field, not only the field's border is highlighted, but also the border of the `<details>` block
<img width="818" alt="Image" src="https://github.com/user-attachments/assets/a34fd735-547c-4608-aaba-a1b4c898f53c" />

**Comment by Elias-Black** [comment]
I've fixed it just for me by adding this:
```css
details {
    padding: 0;
    background: none;
}

summary {
    padding: .5rem 1rem;
    background: var(--b-bg-2);
}

summary:focus {
    outline: none;
    box-shadow: 0 0 0 2px var(--b-focus);
    border-radius: .25rem;
}

details[open] summary:focus {
    border-radius: .25rem .25rem 0 0;
}

details:focus-within {
    outline: none;
    box-shadow: none;
}
```
<img width="797" alt="Image" src="https://github.com/user-attachments/assets/d329d058-0030-4c4b-854e-0eb8a7de5936" />
<img width="810" alt="Image" src="https://github.com/user-attachments/assets/48019211-c052-451f-b405-568218d000b4" />
<img width="799" alt="Image" src="https://github.com/user-attachments/assets/74becfde-e89f-4708-bba2-38750afb2b70" />
